export const locales = {
  it: {
    /*
  ========================================
  BRANDING
  ========================================
  */

    h1: 'Genulux',
    h2: 'Configuratore',
    language: 'Lingua',
    homeConfigurator: 'Home configuratore',
    impressum: 'Note legali',

    /*
  ========================================
  WELCOME
  ========================================
  */

    welcomeTitle: 'Benvenuto nel configuratore AGS',
    welcomeText1: 'Configura il tuo controtelaio in pochi semplici passaggi, scegliendo le caratteristiche più adatte alle tue esigenze.',
    welcomeText2: 'Al termine della configurazione otterrai un riepilogo completo con tutte le misure e le informazioni necessarie.',
    welcomeDescription: 'Configura la tua porta in pochi semplici passaggi. Al termine potrai scaricare un PDF riepilogativo con tutte le misure della configurazione.',
    welcomeFeaturesTitle: 'Durante la configurazione ti verrà richiesto di selezionare:',
    welcomeFeatureDoor: 'Tipo di porta',
    welcomeFeatureWallType: 'Tipo di parete',
    welcomeFeatureWallThickness: 'Spessore della parete',
    welcomeFeatureMeasures: 'Misure della porta',
    savedConfigurationTitle: 'Configurazione trovata',
    savedConfigurationDescription: 'È stata trovata una configurazione salvata. Puoi continuare da dove avevi interrotto oppure iniziare una nuova configurazione.',
    startConfiguration: 'Inizia configurazione',
    continueConfiguration: 'Continua configurazione',
    newConfiguration: 'Nuova configurazione',

    /*
  ========================================
  CONFIGURAZIONE
  ========================================
  */

    door: 'Porta',
    woodDoor: 'Legno 40–44 mm',
    glassDoor: 'Vetro 8–12.7 mm',
    wallType: 'Tipo di muro',
    massivbau: 'Muratura massiva',
    trockenbau: 'Parete in cartongesso',
    wallPanel: 'Pannellatura cartongesso',
    singlePanel: 'Singola lastra',
    doublePanel: 'Doppia lastra',
    wallThickness: 'Spessore muro',
    configurationStandard: 'Standard di configurazione',
    standard: 'Standard',
    selectStandard: 'Seleziona lo standard',
    selectStandardDescription: 'Scegli lo standard di configurazione da utilizzare per il calcolo delle misure.',
    international: 'Internazionale',
    germany: 'DIN/Germania',

    /*
  ========================================
  MISURE
  ========================================
  */

    measures: 'Misure',
    measureType: 'Tipo di misura',
    measureLuce: 'Misura luce',
    measurePorta: 'Misura porta',
    measureMuro: 'Apertura muro',
    insertMeasures: 'Inserisci le misure',
    standardMeasures: 'Misure standard',
    customMeasures: 'Misure libere',
    width: 'Larghezza',
    height: 'Altezza',
    frame: 'Telaio',
    min: 'min',
    max: 'max',

    /*
  ========================================
  DISPONIBILITÀ
  ========================================
  */

    availability: 'Disponibilità',
    availabilityStock: 'Disponibile a magazzino',
    availabilityStockDelivery: 'Consegna rapida',
    availabilityProduction: 'Disponibile su ordinazione',
    availabilityProductionDelivery: 'Tempi di consegna più lunghi',
    availabilityUnavailable: 'Misura non disponibile',
    availabilityContact: 'Contattare il nostro ufficio commerciale',

    /*
  ========================================
  AVVISI
  ========================================
  */

    solidcostructionInfoTitle: 'Informazione per pareti in muratura',
    solidcostructionInfoText: "Per l'installazione su pareti in muratura è necessario prevedere un pannello porta intonaco. Il pannello non è incluso nella fornitura Genulux e dovrà essere procurato separatamente.",

    /*
  ========================================
  RIEPILOGO
  ========================================
  */

    summary: 'Riepilogo',
    technicalMeasuresTitle: 'Misure tecniche',
    insertedMeasureType: 'Tipo misura inserita',
    doorDimensions: 'Misure porta',
    lightPassageDimensions: 'Misure passaggio luce',
    wallOpeningDimensions: 'Misure apertura muro',

    /*
  ========================================
  DOCUMENTO PDF
  ========================================
  */

    documentHeader: 'Scheda tecnica – Configurazione porta',
    documentSubtitle: 'Documento riepilogativo',
    autoGenerated: 'Documento generato automaticamente dal configuratore',

    /*
  ========================================
  RICHIESTA PREVENTIVO
  ========================================
  */

    quoteRequestTitle: 'Richiedi preventivo',
    quoteNameLabel: 'Nome',
    quoteCompanyLabel: 'Azienda',
    quoteEmailLabel: 'Email',
    quotePhoneLabel: 'Telefono',
    quoteCountryLabel: 'Paese',
    quoteCityLabel: 'Città',
    quoteMessageLabel: 'Messaggio',
    quoteNamePlaceholder: 'Nome e Cognome',
    quoteCompanyPlaceholder: 'Azienda',
    quoteEmailPlaceholder: 'Email',
    quotePhonePlaceholder: 'Telefono',
    quoteCountryPlaceholder: 'Nazione',
    quoteCityPlaceholder: 'Città',
    quoteMessagePlaceholder: 'Messaggio',
    quoteSendButton: 'Richiedi preventivo',
    quoteSending: 'Invio...',
    quoteSuccessMessage: 'Richiesta inviata correttamente. Ti ricontatteremo presto.',
    quoteErrorMessage: "Si è verificato un errore durante l'invio della richiesta.",
    quoteFormRequiredFields: 'Compila tutti i campi richiesti',
    quoteFieldRequired: 'Campo obbligatorio',
    quoteFieldInvalid: 'Valore non valido',
    quoteFieldTooLong: 'Testo troppo lungo',
    quoteEmailInvalid: 'Inserisci un indirizzo email valido',
    quotePhoneInvalid: 'Inserisci un numero di telefono valido',

    /*
  ========================================
  AZIONI
  ========================================
  */

    continue: 'Continua',
    downloadPdf: 'Download PDF',

      /*
  ========================================
  IMPRESSUM
  ========================================
  */

    impressumTitle: 'Note legali',

    impressumCompany: 'AGS-systems GmbH',

    impressumHeadquarters: 'Sede legale',
    impressumLogistics: 'Logistica',

    impressumContact: 'Contatti',
    impressumPhone: 'Telefono',
    impressumEmail: 'Email',
    impressumWeb: 'Sito web',

    impressumCompanyData: 'Dati aziendali',
    impressumLegalRepresentative: 'Rappresentante legale',
    impressumRecipientCode: 'Codice destinatario',
    impressumVatNumber: 'Partita IVA',

    impressumOdrTitle: 'Risoluzione delle controversie online UE',
    impressumOdrText1: 'Informativa obbligatoria ai sensi del Regolamento UE n. 524/2013 del Parlamento europeo e del Consiglio:',
    impressumOdrText2: 'Piattaforma per la risoluzione online delle controversie dei consumatori della Commissione europea:',

    impressumDisclaimerTitle: 'Limitazione di responsabilità',
    impressumDisclaimerText1: 'AGS-systems GmbH si impegna, per quanto possibile, a garantire che le informazioni contenute in questo sito web siano corrette.',
    impressumDisclaimerText2: 'Tuttavia, non viene fornita alcuna garanzia né assunta alcuna responsabilità riguardo all’attualità, correttezza o completezza delle informazioni fornite.',
    impressumDisclaimerText3: 'Inoltre, AGS-systems GmbH non è responsabile dei contenuti dei siti web esterni collegati tramite collegamenti ipertestuali.',
    impressumDisclaimerText4: 'AGS-systems GmbH si riserva il diritto di modificare o integrare le informazioni fornite senza preavviso.',

    impressumPrivacyTitle: 'Responsabile del trattamento dei dati personali',
    impressumPrivacyText1: 'Il responsabile del trattamento dei dati personali raccolti e trattati durante l’accesso e l’utilizzo del sito web è AGS-systems GmbH, 39025 Naturno.',
    impressumPrivacyText2: 'Il referente per la protezione dei dati è il Sig. Thomas Alber.',
    impressumPrivacyText3: 'Informazioni dettagliate sulla gestione dei dati personali dei visitatori del sito web sono disponibili nella sezione Privacy.',

    impressumCopyrightImages: 'Fonti immagini',
    impressumCopyright: 'Diritto d’autore',
    impressumCopyrightText1: 'Il layout del sito web, la grafica utilizzata e i contenuti del sito di AGS-systems GmbH sono protetti dal diritto d’autore.',
    impressumCopyrightText2: 'La riproduzione delle informazioni, in particolare l’utilizzo di testi, parti di testi o materiale grafico, richiede la preventiva autorizzazione scritta di AGS-systems GmbH.',
    impressumCopyrightText3: '© AGS-systems GmbH 2025 - Tutti i diritti riservati.',

    impressumBackButton: 'Vai al configuratore'
  },

  en: {
    /*
  ========================================
  BRANDING
  ========================================
  */

    h1: 'Genulux',
    h2: 'Configurator',
    language: 'Language',
    homeConfigurator: 'Configurator Home',
    impressum: 'Legal Notice',

    /*
  ========================================
  WELCOME
  ========================================
  */

    welcomeTitle: 'Welcome to the AGS Configurator',
    welcomeText1: 'Configure your pocket door frame in just a few simple steps by selecting the options that best suit your project.',
    welcomeText2: 'At the end of the process you will receive a complete summary with all dimensions and configuration details.',
    welcomeDescription: 'Configure your door in just a few steps. At the end you will be able to download a PDF summary containing all the configuration measurements.',
    welcomeFeaturesTitle: 'During the configuration you will be asked to select:',
    welcomeFeatureDoor: 'Door type',
    welcomeFeatureWallType: 'Wall type',
    welcomeFeatureWallThickness: 'Wall thickness',
    welcomeFeatureMeasures: 'Door dimensions',
    savedConfigurationTitle: 'Saved configuration found',
    savedConfigurationDescription: 'A previously saved configuration has been found. You can continue where you left off or start a new configuration.',
    startConfiguration: 'Start configuration',
    continueConfiguration: 'Continue configuration',
    newConfiguration: 'New configuration',

    /*
  ========================================
  CONFIGURAZIONE
  ========================================
  */

    door: 'Door',
    woodDoor: 'Wood 40–44 mm',
    glassDoor: 'Glass 8–12.7 mm',
    wallType: 'Wall type',
    massivbau: 'Solid construction',
    trockenbau: 'Drywall construction',
    wallPanel: 'Plasterboard paneling',
    singlePanel: 'Single panel',
    doublePanel: 'Double panel',
    wallThickness: 'Wall thickness',
    configurationStandard: 'Configuration standard',
    standard: 'Standard',
    selectStandard: 'Select standard',
    selectStandardDescription: 'Choose the configuration standard to use for measurements calculation.',
    international: 'International',
    germany: 'DIN/Germany',

    /*
  ========================================
  MISURE
  ========================================
  */

    measures: 'Measurements',
    measureType: 'Measurement type',
    measureLuce: 'Light opening',
    measurePorta: 'Door measurement',
    measureMuro: 'Wall opening',
    insertMeasures: 'Enter measurements',
    standardMeasures: 'Standard measurements',
    customMeasures: 'Custom measurements',
    width: 'Width',
    height: 'Height',
    frame: 'Frame',
    min: 'min',
    max: 'max',

    /*
  ========================================
  DISPONIBILITÀ
  ========================================
  */

    availability: 'Availability',
    availabilityStock: 'Available in stock',
    availabilityStockDelivery: 'Fast delivery',
    availabilityProduction: 'Available on request',
    availabilityProductionDelivery: 'Longer delivery times',
    availabilityUnavailable: 'Size unavailable',
    availabilityContact: 'Contact our sales office',

    /*
  ========================================
  AVVISI
  ========================================
  */

    solidcostructionInfoTitle: 'Information for solid construction walls',
    solidcostructionInfoText: 'For installation in solid construction walls, a plaster carrier panel is required. The panel is not supplied by Genulux and must be sourced separately.',

    /*
  ========================================
  RIEPILOGO
  ========================================
  */

    summary: 'Summary',
    technicalMeasuresTitle: 'Technical measurements',
    insertedMeasureType: 'Inserted measure type',
    doorDimensions: 'Door dimensions',
    lightPassageDimensions: 'Light passage dimensions',
    wallOpeningDimensions: 'Wall opening dimensions',

    /*
  ========================================
  DOCUMENTO PDF
  ========================================
  */

    documentHeader: 'Technical Sheet – Door Configuration',
    documentSubtitle: 'Summary Document',
    autoGenerated: 'Document automatically generated by the configurator',

    /*
  ========================================
  RICHIESTA PREVENTIVO
  ========================================
  */

    quoteRequestTitle: 'Request a quote',
    quoteNameLabel: 'Name',
    quoteCompanyLabel: 'Company',
    quoteEmailLabel: 'Email',
    quotePhoneLabel: 'Phone',
    quoteCountryLabel: 'Country',
    quoteCityLabel: 'City',
    quoteMessageLabel: 'Message',
    quoteNamePlaceholder: 'Full name',
    quoteCompanyPlaceholder: 'Company',
    quoteEmailPlaceholder: 'Email',
    quotePhonePlaceholder: 'Phone',
    quoteCountryPlaceholder: 'Country',
    quoteCityPlaceholder: 'City',
    quoteMessagePlaceholder: 'Message',
    quoteSendButton: 'Request quote',
    quoteSending: 'Sending...',
    quoteSuccessMessage: 'Request sent successfully. We will contact you soon.',
    quoteErrorMessage: 'An error occurred while sending the request.',
    quoteFormRequiredFields: 'Please fill in all required fields',
    quoteFieldRequired: 'Required field',
    quoteFieldInvalid: 'Invalid value',
    quoteFieldTooLong: 'Text too long',
    quoteEmailInvalid: 'Enter a valid email address',
    quotePhoneInvalid: 'Enter a valid phone number',

    /*
  ========================================
  AZIONI
  ========================================
  */

    continue: 'Continue',
    downloadPdf: 'Download PDF',

    /*
  ========================================
  IMPRESSUM
  ========================================
  */

    impressumTitle: 'Legal Notice',

    impressumCompany: 'AGS-systems GmbH',

    impressumHeadquarters: 'Registered office',
    impressumLogistics: 'Logistics',

    impressumContact: 'Contact',
    impressumPhone: 'Phone',
    impressumEmail: 'Email',
    impressumWeb: 'Website',

    impressumCompanyData: 'Company details',
    impressumLegalRepresentative: 'Legal representative',
    impressumRecipientCode: 'Recipient code',
    impressumVatNumber: 'VAT number',

    impressumOdrTitle: 'EU Online Dispute Resolution',
    impressumOdrText1: 'Mandatory information pursuant to EU Regulation No. 524/2013 of the European Parliament and of the Council:',
    impressumOdrText2: 'Platform for the online resolution of consumer disputes (ODR) of the European Commission:',

    impressumDisclaimerTitle: 'Disclaimer',
    impressumDisclaimerText1: 'AGS-systems GmbH strives to ensure, to the best of its ability, that the information contained on this website is accurate.',
    impressumDisclaimerText2: 'However, no liability or guarantee is accepted for the timeliness, accuracy or completeness of the information provided.',
    impressumDisclaimerText3: 'Furthermore, AGS-systems GmbH is not responsible for the content of external websites connected through hyperlinks.',
    impressumDisclaimerText4: 'AGS-systems GmbH reserves the right to modify or supplement the information provided without prior notice.',

    impressumPrivacyTitle: 'Controller of personal data processing',
    impressumPrivacyText1: 'The controller responsible for processing personal data collected and processed during access to and use of the website is AGS-systems GmbH, 39025 Naturns.',
    impressumPrivacyText2: 'The contact person for data protection is Mr. Thomas Alber.',
    impressumPrivacyText3: 'Detailed information about how website visitors’ personal data is managed can be found in the Privacy section.',

    impressumCopyrightImages: 'Image sources',
    impressumCopyright: 'Copyright',
    impressumCopyrightText1: 'The layout of the website, the graphics used and the contents of the AGS-systems GmbH website are protected by copyright.',
    impressumCopyrightText2: 'The reproduction of information, in particular the use of texts, parts of texts or images, requires prior written authorization from AGS-systems GmbH.',
    impressumCopyrightText3: '© AGS-systems GmbH 2025 - All rights reserved.',

    impressumBackButton: 'Go to configurator'
  },

  de: {
    /*
  ========================================
  BRANDING
  ========================================
  */

    h1: 'Genulux',
    h2: 'Konfigurator',
    language: 'Sprache',
    homeConfigurator: 'Konfigurator Startseite',
    impressum: 'Impressum',

    /*
  ========================================
  WELCOME
  ========================================
  */

    welcomeTitle: 'Willkommen beim AGS-Konfigurator',
    welcomeText1: 'Konfigurieren Sie Ihren Schiebetürkasten in wenigen einfachen Schritten und wählen Sie die für Ihr Projekt passenden Eigenschaften aus.',
    welcomeText2: 'Am Ende der Konfiguration erhalten Sie eine vollständige Übersicht mit allen Maßen und den notwendigen Informationen.',
    welcomeDescription: 'Konfigurieren Sie Ihre Tür in wenigen einfachen Schritten. Am Ende können Sie eine PDF-Zusammenfassung mit allen Konfigurationsmaßen herunterladen.',
    welcomeFeaturesTitle: 'Während der Konfiguration werden Sie aufgefordert, Folgendes auszuwählen:',
    welcomeFeatureDoor: 'Türtyp',
    welcomeFeatureWallType: 'Wandtyp',
    welcomeFeatureWallThickness: 'Wandstärke',
    welcomeFeatureMeasures: 'Türmaße',
    savedConfigurationTitle: 'Konfiguration gefunden',
    savedConfigurationDescription: 'Eine gespeicherte Konfiguration wurde gefunden. Sie können dort fortfahren, wo Sie aufgehört haben, oder eine neue Konfiguration starten.',
    startConfiguration: 'Konfiguration starten',
    continueConfiguration: 'Konfiguration fortsetzen',
    newConfiguration: 'Neue Konfiguration',

    /*
  ========================================
  CONFIGURAZIONE
  ========================================
  */

    door: 'Tür',
    woodDoor: 'Holz 40–44 mm',
    glassDoor: 'Glas 8–12.7 mm',
    wallType: 'Wandtyp',
    massivbau: 'Massivbau',
    trockenbau: 'Trockenbau',
    wallPanel: 'Trockenbau-Beplankung',
    singlePanel: 'Einlagige Beplankung',
    doublePanel: 'Doppellagige Beplankung',
    wallThickness: 'Wandstärke',
    configurationStandard: 'Konfigurationsstandard',
    standard: 'Standard',
    selectStandard: 'Standard auswählen',
    selectStandardDescription: 'Wählen Sie den Konfigurationsstandard für die Maßberechnung aus.',
    international: 'International',
    germany: 'DIN/Deutschland',

    /*
  ========================================
  MISURE
  ========================================
  */

    measures: 'Maße',
    measureType: 'Maßtyp',
    measureLuce: 'Lichtöffnung',
    measurePorta: 'Türmaß',
    measureMuro: 'Wandöffnung',
    insertMeasures: 'Maße eingeben',
    standardMeasures: 'Standardmaße',
    customMeasures: 'Freie Maße',
    width: 'Breite',
    height: 'Höhe',
    frame: 'Zarge',
    min: 'min',
    max: 'max',

    /*
  ========================================
  DISPONIBILITÀ
  ========================================
  */

    availability: 'Verfügbarkeit',
    availabilityStock: 'Auf Lager verfügbar',
    availabilityStockDelivery: 'Schnelle Lieferung',
    availabilityProduction: 'Auf Bestellung verfügbar',
    availabilityProductionDelivery: 'Längere Lieferzeiten',
    availabilityUnavailable: 'Maß nicht verfügbar',
    availabilityContact: 'Kontaktieren Sie unser Verkaufsbüro',

    /*
  ========================================
  AVVISI
  ========================================
  */

    solidcostructionInfoTitle: 'Hinweis für Massivbauwände',
    solidcostructionInfoText: 'Für den Einbau in Massivbauwände ist eine Putzträgerplatte erforderlich. Diese ist nicht im Lieferumfang von Genulux enthalten und muss bauseits bereitgestellt werden.',

    /*
  ========================================
  RIEPILOGO
  ========================================
  */

    summary: 'Zusammenfassung',
    technicalMeasuresTitle: 'Technische Maße',
    insertedMeasureType: 'Eingegebener Maßtyp',
    doorDimensions: 'Türmaße',
    lightPassageDimensions: 'Maße der Lichtöffnung',
    wallOpeningDimensions: 'Maße der Wandöffnung',

    /*
  ========================================
  DOCUMENTO PDF
  ========================================
  */

    documentHeader: 'Technisches Datenblatt – Türkonfiguration',
    documentSubtitle: 'Zusammenfassendes Dokument',
    autoGenerated: 'Automatisch vom Konfigurator erstelltes Dokument',

    /*
  ========================================
  RICHIESTA PREVENTIVO
  ========================================
  */

    quoteRequestTitle: 'Angebot anfordern',
    quoteNameLabel: 'Name',
    quoteCompanyLabel: 'Firma',
    quoteEmailLabel: 'E-Mail',
    quotePhoneLabel: 'Telefon',
    quoteCountryLabel: 'Land',
    quoteCityLabel: 'Stadt',
    quoteMessageLabel: 'Nachricht',
    quoteNamePlaceholder: 'Vor- und Nachname',
    quoteCompanyPlaceholder: 'Firma',
    quoteEmailPlaceholder: 'E-Mail',
    quotePhonePlaceholder: 'Telefon',
    quoteCountryPlaceholder: 'Land',
    quoteCityPlaceholder: 'Stadt',
    quoteMessagePlaceholder: 'Nachricht',
    quoteSendButton: 'Angebot anfordern',
    quoteSending: 'Senden...',
    quoteSuccessMessage: 'Anfrage erfolgreich gesendet. Wir werden Sie bald kontaktieren.',
    quoteErrorMessage: 'Beim Senden der Anfrage ist ein Fehler aufgetreten.',
    quoteFormRequiredFields: 'Bitte füllen Sie alle Pflichtfelder aus',
    quoteFieldRequired: 'Pflichtfeld',
    quoteFieldInvalid: 'Ungültiger Wert',
    quoteFieldTooLong: 'Text zu lang',
    quoteEmailInvalid: 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
    quotePhoneInvalid: 'Bitte geben Sie eine gültige Telefonnummer ein',

    /*
  ========================================
  AZIONI
  ========================================
  */

    continue: 'Weiter',
    downloadPdf: 'PDF herunterladen',

    /*
  ========================================
  IMPRESSUM
  ========================================
  */

    impressumTitle: 'Impressum',

    impressumCompany: 'AGS-systems GmbH',

    impressumHeadquarters: 'Geschäftssitz',
    impressumLogistics: 'Logistik',

    impressumContact: 'Kontakt',
    impressumPhone: 'Telefon',
    impressumEmail: 'Email',
    impressumWeb: 'Web',

    impressumCompanyData: 'Unternehmensdaten',
    impressumLegalRepresentative: 'Gesetzlicher Vertreter',
    impressumRecipientCode: 'Empfängerkodex',
    impressumVatNumber: 'MwSt.-Nr.',

    impressumOdrTitle: 'EU Online-Streitbeilegung',
    impressumOdrText1: 'Pflichtinformation nach EU-Verordnung Nr. 524/2013 des Europäischen Parlaments und Rats:',
    impressumOdrText2: 'Plattform zur Online-Beilegung verbraucherrechtlicher Streitigkeiten (ODR) der Europäischen Kommission:',

    impressumDisclaimerTitle: 'Haftungsausschluss',
    impressumDisclaimerText1: 'Die AGS-systems GmbH bemüht sich, nach bestem Vermögen dafür Sorge zu tragen, dass die in diesem Internetauftritt enthaltenen Informationen zutreffend sind.',
    impressumDisclaimerText2: 'Eine Haftung oder Garantie für die Aktualität, Richtigkeit und Vollständigkeit der zur Verfügung gestellten Informationen ist jedoch ausgeschlossen.',
    impressumDisclaimerText3: 'Ferner ist die AGS-systems GmbH für den Inhalt der über Hyperlink extern verbundenen Internetauftritte nicht verantwortlich.',
    impressumDisclaimerText4: 'Die AGS-systems GmbH behält sich vor, ohne Ankündigung, Änderungen oder Ergänzungen der bereitgestellten Informationen vorzunehmen.',

    impressumPrivacyTitle: 'Verantwortlicher der Verarbeitung personenbezogener Daten',
    impressumPrivacyText1: 'Verantwortlich für die Verarbeitung personenbezogener Daten, die bei Website-Zugriff und -Benutzung erhoben und verarbeitet werden, ist die AGS-systems GmbH, 39025 Naturns.',
    impressumPrivacyText2: 'Ansprechpartner für den Datenschutz ist Herr Thomas Alber.',
    impressumPrivacyText3: 'Detaillierte Informationen darüber, wie die personenbezogenen Daten der Website-Besucher verwaltet werden, finden Sie unter dem Punkt Datenschutz.',

    impressumCopyrightImages: 'Bildquellen',
    impressumCopyright: 'Urheberrecht',
    impressumCopyrightText1: 'Das Layout der Homepage, die verwendeten Grafiken sowie die Inhalte des Internetauftritts der AGS-systems GmbH sind urheberrechtlich geschützt.',
    impressumCopyrightText2: 'Die Vervielfältigung von Informationen, insbesondere die Verwendung von Texten, Textteilen oder Bildmaterial bedarf der vorherigen schriftlichen Genehmigung der AGS-systems GmbH.',
    impressumCopyrightText3: '© AGS-systems GmbH 2025 - Alle Rechte vorbehalten.',

    impressumBackButton: 'Zum Konfigurator'
  },

  es: {
    /*
  ========================================
  BRANDING
  ========================================
  */

    h1: 'Genulux',
    h2: 'Configurador',
    language: 'Idioma',
    homeConfigurator: 'Inicio configurador',
    impressum: 'Aviso legal',

    /*
  ========================================
  WELCOME
  ========================================
  */

    welcomeTitle: 'Bienvenido al configurador AGS',
    welcomeText1: 'Configure su contamarco para puerta corredera en unos sencillos pasos, seleccionando las características más adecuadas para sus necesidades.',
    welcomeText2: 'Al finalizar la configuración obtendrá un resumen completo con todas las medidas y la información necesaria.',
    welcomeDescription: 'Configure su puerta en pocos pasos. Al finalizar podrá descargar un PDF resumen con todas las medidas de la configuración.',
    welcomeFeaturesTitle: 'Durante la configuración deberá seleccionar:',
    welcomeFeatureDoor: 'Tipo de puerta',
    welcomeFeatureWallType: 'Tipo de pared',
    welcomeFeatureWallThickness: 'Espesor de la pared',
    welcomeFeatureMeasures: 'Medidas de la puerta',
    savedConfigurationTitle: 'Configuración encontrada',
    savedConfigurationDescription: 'Se ha encontrado una configuración guardada. Puede continuar desde donde lo dejó o iniciar una nueva configuración.',
    startConfiguration: 'Iniciar configuración',
    continueConfiguration: 'Continuar configuración',
    newConfiguration: 'Nueva configuración',

    /*
  ========================================
  CONFIGURAZIONE
  ========================================
  */

    door: 'Puerta',
    woodDoor: 'Madera 40–44 mm',
    glassDoor: 'Vidrio 8–12.7 mm',
    wallType: 'Tipo de pared',
    massivbau: 'Construcción maciza',
    trockenbau: 'Construcción de cartón yeso',
    wallPanel: 'Panelado de cartón yeso',
    singlePanel: 'Placa simple',
    doublePanel: 'Doble placa',
    wallThickness: 'Espesor de pared',
    configurationStandard: 'Estándar de configuración',
    standard: 'Estándar',
    selectStandard: 'Selecciona el estándar',
    selectStandardDescription: 'Elige el estándar de configuración que se utilizará para el cálculo de las medidas.',
    international: 'Internacional',
    germany: 'DIN/Alemania',

    /*
  ========================================
  MISURE
  ========================================
  */

    measures: 'Medidas',
    measureType: 'Tipo de medida',
    measureLuce: 'Medida de luz',
    measurePorta: 'Medida de puerta',
    measureMuro: 'Apertura de pared',
    insertMeasures: 'Introducir las medidas',
    standardMeasures: 'Medidas estándar',
    customMeasures: 'Medidas libres',
    width: 'Ancho',
    height: 'Alto',
    frame: 'Marco',
    min: 'mín',
    max: 'máx',

    /*
  ========================================
  DISPONIBILITÀ
  ========================================
  */

    availability: 'Disponibilidad',
    availabilityStock: 'Disponible en stock',
    availabilityStockDelivery: 'Entrega rápida',
    availabilityProduction: 'Disponible bajo pedido',
    availabilityProductionDelivery: 'Tiempos de entrega más largos',
    availabilityUnavailable: 'Medida no disponible',
    availabilityContact: 'Contactar con nuestra oficina comercial',

    /*
  ========================================
  AVVISI
  ========================================
  */

    solidcostructionInfoTitle: 'Información para paredes de mampostería',
    solidcostructionInfoText: 'Para la instalación en paredes de mampostería es necesario prever un panel portaenlucido. Este panel no está incluido en el suministro de Genulux y deberá adquirirse por separado.',

    /*
  ========================================
  RIEPILOGO
  ========================================
  */

    summary: 'Resumen',
    technicalMeasuresTitle: 'Medidas técnicas',
    insertedMeasureType: 'Tipo de medida introducida',
    doorDimensions: 'Medidas de la puerta',
    lightPassageDimensions: 'Medidas del paso de luz',
    wallOpeningDimensions: 'Medidas de la apertura de pared',

    /*
  ========================================
  DOCUMENTO PDF
  ========================================
  */

    documentHeader: 'Ficha técnica – Configuración de puerta',
    documentSubtitle: 'Documento resumen',
    autoGenerated: 'Documento generado automáticamente por el configurador',

    /*
  ========================================
  RICHIESTA PREVENTIVO
  ========================================
  */

    quoteRequestTitle: 'Solicitar presupuesto',
    quoteNameLabel: 'Nombre',
    quoteCompanyLabel: 'Empresa',
    quoteEmailLabel: 'Correo electrónico',
    quotePhoneLabel: 'Teléfono',
    quoteCountryLabel: 'País',
    quoteCityLabel: 'Ciudad',
    quoteMessageLabel: 'Mensaje',
    quoteNamePlaceholder: 'Nombre y apellidos',
    quoteCompanyPlaceholder: 'Empresa',
    quoteEmailPlaceholder: 'Correo electrónico',
    quotePhonePlaceholder: 'Teléfono',
    quoteCountryPlaceholder: 'País',
    quoteCityPlaceholder: 'Ciudad',
    quoteMessagePlaceholder: 'Mensaje',
    quoteSendButton: 'Solicitar presupuesto',
    quoteSending: 'Enviando...',
    quoteSuccessMessage: 'Solicitud enviada correctamente. Nos pondremos en contacto pronto.',
    quoteErrorMessage: 'Se produjo un error al enviar la solicitud.',
    quoteFormRequiredFields: 'Complete todos los campos obligatorios',
    quoteFieldRequired: 'Campo obligatorio',
    quoteFieldInvalid: 'Valor no válido',
    quoteFieldTooLong: 'Texto demasiado largo',
    quoteEmailInvalid: 'Introduzca un correo electrónico válido',
    quotePhoneInvalid: 'Introduzca un número de teléfono válido',

    /*
  ========================================
  AZIONI
  ========================================
  */

    continue: 'Continuar',
    downloadPdf: 'Descargar PDF',

    /*
  ========================================
  IMPRESSUM
  ========================================
  */

    impressumTitle: 'Aviso legal',

    impressumCompany: 'AGS-systems GmbH',

    impressumHeadquarters: 'Sede social',
    impressumLogistics: 'Logística',

    impressumContact: 'Contacto',
    impressumPhone: 'Teléfono',
    impressumEmail: 'Correo electrónico',
    impressumWeb: 'Sitio web',

    impressumCompanyData: 'Datos de la empresa',
    impressumLegalRepresentative: 'Representante legal',
    impressumRecipientCode: 'Código destinatario',
    impressumVatNumber: 'Número de IVA',

    impressumOdrTitle: 'Resolución de litigios en línea de la UE',
    impressumOdrText1: 'Información obligatoria conforme al Reglamento UE n.º 524/2013 del Parlamento Europeo y del Consejo:',
    impressumOdrText2: 'Plataforma de resolución en línea de litigios de consumidores (ODR) de la Comisión Europea:',

    impressumDisclaimerTitle: 'Exención de responsabilidad',
    impressumDisclaimerText1: 'AGS-systems GmbH se esfuerza por garantizar, en la medida de sus posibilidades, que la información contenida en este sitio web sea correcta.',
    impressumDisclaimerText2: 'Sin embargo, no se acepta ninguna responsabilidad ni garantía sobre la actualidad, exactitud o integridad de la información proporcionada.',
    impressumDisclaimerText3: 'Además, AGS-systems GmbH no se responsabiliza del contenido de sitios web externos enlazados mediante hipervínculos.',
    impressumDisclaimerText4: 'AGS-systems GmbH se reserva el derecho de modificar o completar la información proporcionada sin previo aviso.',

    impressumPrivacyTitle: 'Responsable del tratamiento de datos personales',
    impressumPrivacyText1: 'El responsable del tratamiento de los datos personales recopilados y procesados durante el acceso y uso del sitio web es AGS-systems GmbH, 39025 Naturns.',
    impressumPrivacyText2: 'El responsable de contacto para la protección de datos es el Sr. Thomas Alber.',
    impressumPrivacyText3: 'Puede encontrar información detallada sobre la gestión de los datos personales de los visitantes del sitio web en la sección Privacidad.',

    impressumCopyrightImages: 'Fuentes de imágenes',
    impressumCopyright: 'Derechos de autor',
    impressumCopyrightText1: 'El diseño del sitio web, los gráficos utilizados y los contenidos del sitio de AGS-systems GmbH están protegidos por derechos de autor.',
    impressumCopyrightText2: 'La reproducción de información, especialmente el uso de textos, partes de textos o material gráfico, requiere la autorización previa por escrito de AGS-systems GmbH.',
    impressumCopyrightText3: '© AGS-systems GmbH 2025 - Todos los derechos reservados.',

    impressumBackButton: 'Ir al configurador'
  },

  fr: {
    /*
  ========================================
  BRANDING
  ========================================
  */

    h1: 'Genulux',
    h2: 'Configurateur',
    language: 'Langue',
    homeConfigurator: 'Accueil configurateur',
    impressum: 'Mentions légales',

    /*
  ========================================
  WELCOME
  ========================================
  */

    welcomeTitle: 'Bienvenue dans le configurateur AGS',
    welcomeText1: 'Configurez votre châssis de porte coulissante en quelques étapes simples en choisissant les caractéristiques les plus adaptées à vos besoins.',
    welcomeText2: 'À la fin de la configuration, vous obtiendrez un récapitulatif complet avec toutes les dimensions et les informations nécessaires.',
    welcomeDescription: 'Configurez votre porte en quelques étapes simples. À la fin, vous pourrez télécharger un PDF récapitulatif contenant toutes les dimensions de la configuration.',
    welcomeFeaturesTitle: 'Pendant la configuration, vous devrez sélectionner :',
    welcomeFeatureDoor: 'Type de porte',
    welcomeFeatureWallType: 'Type de cloison',
    welcomeFeatureWallThickness: 'Épaisseur de la cloison',
    welcomeFeatureMeasures: 'Dimensions de la porte',
    savedConfigurationTitle: 'Configuration trouvée',
    savedConfigurationDescription: 'Une configuration enregistrée a été trouvée. Vous pouvez reprendre là où vous vous êtes arrêté ou commencer une nouvelle configuration.',
    startConfiguration: 'Commencer la configuration',
    continueConfiguration: 'Continuer la configuration',
    newConfiguration: 'Nouvelle configuration',

    /*
  ========================================
  CONFIGURAZIONE
  ========================================
  */

    door: 'Porte',
    woodDoor: 'Bois 40–44 mm',
    glassDoor: 'Verre 8–12.7 mm',
    wallType: 'Type de mur',
    massivbau: 'Maçonnerie massive',
    trockenbau: 'Cloison en plaques de plâtre',
    wallPanel: 'Panneaux en plaques de plâtre',
    singlePanel: 'Simple plaque',
    doublePanel: 'Double plaque',
    wallThickness: 'Épaisseur du mur',
    configurationStandard: 'Standard de configuration',
    standard: 'Standard',
    selectStandard: 'Sélectionnez le standard',
    selectStandardDescription: 'Choisissez le standard de configuration à utiliser pour le calcul des dimensions.',
    international: 'International',
    germany: 'DIN/Allemagne',

    /*
  ========================================
  MISURE
  ========================================
  */

    measures: 'Mesures',
    measureType: 'Type de mesure',
    measureLuce: 'Mesure du passage libre',
    measurePorta: 'Mesure de la porte',
    measureMuro: 'Ouverture du mur',
    insertMeasures: 'Saisir les mesures',
    standardMeasures: 'Mesures standard',
    customMeasures: 'Mesures personnalisées',
    width: 'Largeur',
    height: 'Hauteur',
    frame: 'Huisserie',
    min: 'min',
    max: 'max',

    /*
  ========================================
  DISPONIBILITÀ
  ========================================
  */

    availability: 'Disponibilité',
    availabilityStock: 'Disponible en stock',
    availabilityStockDelivery: 'Livraison rapide',
    availabilityProduction: 'Disponible sur commande',
    availabilityProductionDelivery: 'Délais de livraison plus longs',
    availabilityUnavailable: 'Dimension non disponible',
    availabilityContact: 'Contacter notre service commercial',

    /*
  ========================================
  AVVISI
  ========================================
  */

    solidcostructionInfoTitle: 'Information pour les murs maçonnés',
    solidcostructionInfoText: "Pour l'installation dans des murs maçonnés, un panneau support d'enduit est nécessaire. Ce panneau n'est pas inclus dans la fourniture Genulux et doit être fourni séparément.",

    /*
  ========================================
  RIEPILOGO
  ========================================
  */

    summary: 'Résumé',
    technicalMeasuresTitle: 'Mesures techniques',
    insertedMeasureType: 'Type de mesure saisie',
    doorDimensions: 'Dimensions de la porte',
    lightPassageDimensions: 'Dimensions du passage libre',
    wallOpeningDimensions: "Dimensions de l'ouverture du mur",

    /*
  ========================================
  DOCUMENTO PDF
  ========================================
  */

    documentHeader: 'Fiche technique – Configuration de porte',
    documentSubtitle: 'Document récapitulatif',
    autoGenerated: 'Document généré automatiquement par le configurateur',

    /*
  ========================================
  RICHIESTA PREVENTIVO
  ========================================
  */

    quoteRequestTitle: 'Demander un devis',
    quoteNameLabel: 'Nom',
    quoteCompanyLabel: 'Entreprise',
    quoteEmailLabel: 'E-mail',
    quotePhoneLabel: 'Téléphone',
    quoteCountryLabel: 'Pays',
    quoteCityLabel: 'Ville',
    quoteMessageLabel: 'Message',
    quoteNamePlaceholder: 'Nom et prénom',
    quoteCompanyPlaceholder: 'Entreprise',
    quoteEmailPlaceholder: 'E-mail',
    quotePhonePlaceholder: 'Téléphone',
    quoteCountryPlaceholder: 'Pays',
    quoteCityPlaceholder: 'Ville',
    quoteMessagePlaceholder: 'Message',
    quoteSendButton: 'Demander un devis',
    quoteSending: 'Envoi...',
    quoteSuccessMessage: 'Demande envoyée avec succès. Nous vous contacterons bientôt.',
    quoteErrorMessage: "Une erreur s'est produite lors de l'envoi de la demande.",
    quoteFormRequiredFields: 'Veuillez remplir tous les champs obligatoires',
    quoteFieldRequired: 'Champ obligatoire',
    quoteFieldInvalid: 'Valeur invalide',
    quoteFieldTooLong: 'Texte trop long',
    quoteEmailInvalid: 'Saisissez une adresse e-mail valide',
    quotePhoneInvalid: 'Saisissez un numéro de téléphone valide',

    /*
  ========================================
  AZIONI
  ========================================
  */

    continue: 'Continuer',
    downloadPdf: 'Télécharger le PDF',

      /*
  ========================================
  IMPRESSUM
  ========================================
  */

    impressumTitle: 'Mentions légales',

    impressumCompany: 'AGS-systems GmbH',

    impressumHeadquarters: 'Siège social',
    impressumLogistics: 'Logistique',

    impressumContact: 'Contact',
    impressumPhone: 'Téléphone',
    impressumEmail: 'E-mail',
    impressumWeb: 'Site web',

    impressumCompanyData: 'Données de l’entreprise',
    impressumLegalRepresentative: 'Représentant légal',
    impressumRecipientCode: 'Code destinataire',
    impressumVatNumber: 'Numéro de TVA',

    impressumOdrTitle: 'Règlement en ligne des litiges de l’UE',
    impressumOdrText1: 'Information obligatoire conformément au règlement UE n° 524/2013 du Parlement européen et du Conseil :',
    impressumOdrText2: 'Plateforme de règlement en ligne des litiges de consommation (ODR) de la Commission européenne :',

    impressumDisclaimerTitle: 'Clause de non-responsabilité',
    impressumDisclaimerText1: 'AGS-systems GmbH s’efforce de garantir, dans la mesure de ses possibilités, que les informations contenues sur ce site internet sont exactes.',
    impressumDisclaimerText2: 'Toutefois, aucune responsabilité ni garantie n’est assumée concernant l’actualité, l’exactitude ou l’exhaustivité des informations fournies.',
    impressumDisclaimerText3: 'AGS-systems GmbH n’est pas responsable du contenu des sites internet externes accessibles via des liens hypertextes.',
    impressumDisclaimerText4: 'AGS-systems GmbH se réserve le droit de modifier ou de compléter les informations fournies sans préavis.',

    impressumPrivacyTitle: 'Responsable du traitement des données personnelles',
    impressumPrivacyText1: 'Le responsable du traitement des données personnelles collectées et traitées lors de l’accès et de l’utilisation du site internet est AGS-systems GmbH, 39025 Naturns.',
    impressumPrivacyText2: 'Le contact pour la protection des données est Monsieur Thomas Alber.',
    impressumPrivacyText3: 'Des informations détaillées sur la gestion des données personnelles des visiteurs du site sont disponibles dans la section Confidentialité.',

    impressumCopyrightImages: 'Sources des images',
    impressumCopyright: 'Droits d’auteur',
    impressumCopyrightText1: 'La mise en page du site internet, les graphiques utilisés ainsi que les contenus du site AGS-systems GmbH sont protégés par le droit d’auteur.',
    impressumCopyrightText2: 'La reproduction d’informations, notamment l’utilisation de textes, parties de textes ou images, nécessite l’autorisation écrite préalable d’AGS-systems GmbH.',
    impressumCopyrightText3: '© AGS-systems GmbH 2025 - Tous droits réservés.',

    impressumBackButton: 'Accéder au configurateur'
  }
};
