export const locales = {
  it: {

    technicalMeasuresTitle: "Misure tecniche",

    impressum: "Note legali",

    language: "Lingua",
    homeConfigurator: 'Home configuratore',

    // Branding
    h1: "Genulux",
    h2: "Configuratore",

    // Configurazione
    door: "Porta",
    wallThickness: "Spessore muro",
    configurationStandard: "Standard di configurazione",

    // Riepilogo
    insertedMeasureType: "Tipo misura inserita",
    doorDimensions: "Misure Porta",
    lightPassageDimensions: "Misure passaggio Luce",
    wallOpeningDimensions: "Misure apertura Muro",

    // Misure
    measures: "Misure",
    summary: "Riepilogo",
    insertMeasures: "Inserisci le misure",
    measureType: "Tipo di misura",
    standardMeasures: "Misure standard",
    customMeasures: "Misure libere",
    width: "Larghezza",
    height: "Altezza",
    frame: "Telaio",

    // Azioni
    continue: "Continua",
    newConfiguration: "Nuova configurazione",
    downloadPdf: "Download PDF",

    // Limiti
    min: "min",
    max: "max",

    // Documento PDF
    documentHeader: "Scheda tecnica – Configurazione porta",
    documentSubtitle: "Documento riepilogativo",
    autoGenerated: "Documento generato automaticamente dal configuratore",

    // Tipi di misura
    measureLuce: "Misura luce",
    measurePorta: "Misura porta",
    measureMuro: "Apertura muro",

    // Standard
    standard: "Standard",
    selectStandard: "Seleziona lo standard",
    selectStandardDescription: "Scegli lo standard di configurazione da utilizzare per il calcolo delle misure.",
    international: "Internazionale",
    germany: "DIN/Germania",

    // Disponibilità misure
    availability: "Disponibilità",

    availabilityStock: "Disponibile a magazzino",
    availabilityStockDelivery: "Consegna rapida",

    availabilityProduction: "Disponibile su ordinazione",
    availabilityProductionDelivery: "Tempi di consegna più lunghi",

    availabilityUnavailable: "Misura non disponibile",
    availabilityContact: "Contattare il nostro ufficio commerciale",

    // Tipo di porta
    woodDoor: 'Legno 40–44 mm',
    glassDoor: 'Vetro 8–12.7 mm',


    // WALL TYPES
    wallType: 'Tipo di muro',
    massivbau: 'Muratura massiva',
    trockenbau: 'Parete in cartongesso',

    // Tipo muro - pannellatura cartongesso
    wallPanel: 'Pannellatura cartongesso',
    singlePanel: 'Singola lastra',
    doublePanel: 'Doppia lastra',


    // Welcome configuratore

    welcomeTitle: "Benvenuto nel configuratore AGS",
    welcomeText1: "Configura il tuo controtelaio in pochi semplici passaggi, scegliendo le caratteristiche più adatte alle tue esigenze.",
    welcomeText2: "Al termine della configurazione otterrai un riepilogo completo con tutte le misure e le informazioni necessarie.",

    welcomeDescription:'Configura la tua porta in pochi semplici passaggi. Al termine potrai scaricare un PDF riepilogativo con tutte le misure della configurazione.',
    welcomeFeaturesTitle: 'Durante la configurazione ti verrà richiesto di selezionare:',
    welcomeFeatureDoor: 'Tipo di porta',
    welcomeFeatureWallType: 'Tipo di parete',
    welcomeFeatureWallThickness: 'Spessore della parete',
    welcomeFeatureMeasures: 'Misure della porta',
    savedConfigurationTitle: 'Configurazione trovata',
    savedConfigurationDescription:'È stata trovata una configurazione salvata. Puoi continuare da dove avevi interrotto oppure iniziare una nuova configurazione.',
    startConfiguration: 'Inizia configurazione',
    continueConfiguration: 'Continua configurazione',
    newConfiguration: 'Nuova configurazione',

    solidcostructionInfoTitle: "Informazione per pareti in muratura",
    solidcostructionInfoText:"Per l'installazione su pareti in muratura è necessario prevedere un pannello porta intonaco. Il pannello non è incluso nella fornitura Genulux e dovrà essere procurato separatamente.",


    quoteRequestTitle: "Richiedi preventivo",

    quoteNamePlaceholder: "Nome e Cognome",

    quoteCompanyPlaceholder: "Azienda",

    quoteEmailPlaceholder: "Email",

    quotePhonePlaceholder: "Telefono",

    quoteCountryPlaceholder: "Nazione",

    quoteCityPlaceholder: "Città",

    quoteMessagePlaceholder: "Messaggio",

    quoteSendButton: "Richiedi preventivo",

    quoteSending: "Invio...",

    quoteSuccessMessage: "Richiesta inviata correttamente. Ti ricontatteremo presto.",

    quoteErrorMessage: "Si è verificato un errore durante l'invio della richiesta.",

    quoteFormRequiredFields: "Compila tutti i campi richiesti",

    quoteFieldRequired:
      'Campo obbligatorio',

    quoteFieldInvalid:
      'Valore non valido',

    quoteFieldTooLong:
      'Testo troppo lungo',
      
      quoteNameLabel:
        'Nome',

      quoteCompanyLabel:
        'Azienda',

      quoteEmailLabel:
        'Email',

      quotePhoneLabel:
        'Telefono',

      quoteCountryLabel:
        'Paese',

      quoteCityLabel:
        'Città',

      quoteMessageLabel:
        'Messaggio',

      quoteEmailInvalid:
      'Inserisci un indirizzo email valido',

    quotePhoneInvalid:
      'Inserisci un numero di telefono valido',
  },
      
  en: {

    technicalMeasuresTitle: "Technical measurements",

    impressum: "Legal Notice",

    language: "Language",

    homeConfigurator: 'Configurator Home',

    // Branding
    h1: "Genulux",
    h2: "Configurator",

    // Configurazione
    door: "Door",
    wallThickness: "Wall Thickness",
    configurationStandard: "Configuration standard",

    // Riepilogo
    insertedMeasureType: "Inserted Measure Type",
    doorDimensions: "Door Dimensions",
    lightPassageDimensions: "Light Passage Dimensions",
    wallOpeningDimensions: "Wall Opening Dimensions",

    // Misure
    measures: "Measurements",
    summary: "Summary",
    insertMeasures: "Enter measurements",
    measureType: "Measurement type",
    standardMeasures: "Standard measurements",
    customMeasures: "Custom measurements",
    width: "Width",
    height: "Height",
    frame: "Frame",

    // Azioni
    continue: "Continue",
    newConfiguration: "New configuration",
    downloadPdf: "Download PDF",

    // Limiti
    min: "min",
    max: "max",

    // Documento PDF
    documentHeader: "Technical Sheet – Door Configuration",
    documentSubtitle: "Summary Document",
    autoGenerated: "Document automatically generated by the configurator",

    // Tipi di misura
    measureLuce: "Light opening",
    measurePorta: "Door measurement",
    measureMuro: "Wall opening",

    // Standard
    standard: "Standard",
    selectStandard: "Select standard",
    selectStandardDescription: "Choose the configuration standard to use for measurements calculation.",
    international: "International",
    germany: "DIN/Germany",

    // Availability
    availability: "Availability",

    availabilityStock: "Available in stock",
    availabilityStockDelivery: "Fast delivery",

    availabilityProduction: "Available on request",
    availabilityProductionDelivery: "Longer delivery times",

    availabilityUnavailable: "Size unavailable",
    availabilityContact: "Contact our sales office",

    // Tipo di porta
    woodDoor: 'Wood 40–44 mm',
    glassDoor: 'Glass 8–12.7 mm',

    // WALL TYPES
    wallType: 'Wall type',
    massivbau: 'Solid construction',
    trockenbau: 'Drywall construction',

    // Wall type - plasterboard paneling
    wallPanel: 'Plasterboard paneling',
    singlePanel: 'Single panel',
    doublePanel: 'Double panel',
    
    // Welcome configuratore
    welcomeTitle: "Welcome to the AGS Configurator",
    welcomeText1: "Configure your pocket door frame in just a few simple steps by selecting the options that best suit your project.",
    welcomeText2: "At the end of the process you will receive a complete summary with all dimensions and configuration details.",

    welcomeDescription:'Configure your door in just a few steps. At the end you will be able to download a PDF summary containing all the configuration measurements.',
    welcomeFeaturesTitle: 'During the configuration you will be asked to select:',
    welcomeFeatureDoor: 'Door type',
    welcomeFeatureWallType: 'Wall type',
    welcomeFeatureWallThickness: 'Wall thickness',
    welcomeFeatureMeasures: 'Door dimensions',
    savedConfigurationTitle: 'Saved configuration found',
    savedConfigurationDescription:'A previously saved configuration has been found. You can continue where you left off or start a new configuration.',
    startConfiguration: 'Start configuration',
    continueConfiguration: 'Continue configuration',
    newConfiguration: 'New configuration',

    solidcostructionInfoTitle: "Information for solidcostruction walls",
    solidcostructionInfoText:"For installation in solidcostruction walls, a plaster carrier panel is required. The panel is not supplied by Genulux and must be sourced separately.",


    quoteRequestTitle: "Request a quote",

    quoteNamePlaceholder: "Full name",

    quoteCompanyPlaceholder: "Company",

    quoteEmailPlaceholder: "Email",

    quotePhonePlaceholder: "Phone",

    quoteCountryPlaceholder: "Country",

    quoteCityPlaceholder: "City",

    quoteMessagePlaceholder: "Message",

    quoteSendButton: "Request quote",

    quoteSending: "Sending...",

    quoteSuccessMessage: "Request sent successfully. We will contact you soon.",

    quoteErrorMessage: "An error occurred while sending the request.",

    quoteFormRequiredFields: "Please fill in all required fields",

    quoteFieldRequired:
      'Required field',

    quoteFieldInvalid:
      'Invalid value',

    quoteFieldTooLong:
      'Text too long',

    quoteNameLabel:
      'Name',

    quoteCompanyLabel:
      'Company',

    quoteEmailLabel:
      'Email',

    quotePhoneLabel:
      'Phone',

    quoteCountryLabel:
      'Country',

    quoteCityLabel:
      'City',

    quoteMessageLabel:
      'Message',

      quoteEmailInvalid:
        'Enter a valid email address',

      quotePhoneInvalid:
        'Enter a valid phone number',
  },

  de: {

    technicalMeasuresTitle: "Technische Maße",

    impressum: "Impressum",

    language: "Sprache",

    homeConfigurator: 'Konfigurator Startseite',

    // Branding
    h1: "Genulux",
    h2: "Konfigurator",

    // Configurazione
    door: "Tür",
    wallThickness: "Wandstärke",
    configurationStandard: "Konfigurationsstandard",

    // Riepilogo
    insertedMeasureType: "Eingegebener Maßtyp",
    doorDimensions: "Türmaße",
    lightPassageDimensions: "Maße der Lichtöffnung",
    wallOpeningDimensions: "Maße der Wandöffnung",

    // Misure
    measures: "Maße",
    summary: "Zusammenfassung",
    insertMeasures: "Maße eingeben",
    measureType: "Maßtyp",
    standardMeasures: "Standardmaße",
    customMeasures: "Freie Maße",
    width: "Breite",
    height: "Höhe",
    frame: "Zarge",

    // Azioni
    continue: "Weiter",
    newConfiguration: "Neue Konfiguration",
    downloadPdf: "PDF herunterladen",

    // Limiti
    min: "min",
    max: "max",

    // Documento PDF
    documentHeader: "Technisches Blatt – Türkonfiguration",
    documentSubtitle: "Zusammenfassendes Dokument",
    autoGenerated: "Automatisch vom Konfigurator generiertes Dokument",

    // Tipi di misura
    measureLuce: "Lichtöffnung",
    measurePorta: "Türmaß",
    measureMuro: "Wandöffnung",

    // Standard
    standard: "Standard",
    selectStandard: "Standard auswählen",
    selectStandardDescription: "Wählen Sie den Konfigurationsstandard für die Maßberechnung.",
    international: "International",
    germany: "DIN/Deutschland",

    // Verfügbarkeit
    availability: "Verfügbarkeit",

    availabilityStock: "Auf Lager verfügbar",
    availabilityStockDelivery: "Schnelle Lieferung",

    availabilityProduction: "Auf Bestellung verfügbar",
    availabilityProductionDelivery: "Längere Lieferzeiten",

    availabilityUnavailable: "Maß nicht verfügbar",
    availabilityContact: "Kontaktieren Sie unser Verkaufsbüro",

    //Tipo di porta
    woodDoor: 'Holz 40–44 mm',
    glassDoor: 'Glas 8–12.7 mm',

    // WALL TYPES
    wallType: 'Wandtyp',
    massivbau: 'Massivbau',
    trockenbau: 'Trockenbau',

    // Wandtyp - Trockenbau Beplankung
    wallPanel: 'Trockenbau Beplankung',
    singlePanel: 'Einlagige Beplankung',
    doublePanel: 'Doppellagige Beplankung',


    // Welcome configuratore

    welcomeTitle: "Willkommen beim AGS-Konfigurator",
    welcomeText1: "Konfigurieren Sie Ihren Schiebetürkasten in nur wenigen Schritten entsprechend Ihren Anforderungen.",
    welcomeText2: "Am Ende der Konfiguration erhalten Sie eine vollständige Übersicht mit allen Maßen und den gewählten Einstellungen.",


    welcomeDescription:'Konfigurieren Sie Ihre Tür in wenigen Schritten. Am Ende können Sie eine PDF-Zusammenfassung mit allen Maßen herunterladen.',
    welcomeFeaturesTitle: 'Während der Konfiguration wählen Sie aus:',
    welcomeFeatureDoor: 'Türtyp',
    welcomeFeatureWallType: 'Wandtyp',
    welcomeFeatureWallThickness: 'Wandstärke',
    welcomeFeatureMeasures: 'Türmaße',
    savedConfigurationTitle: 'Gespeicherte Konfiguration gefunden',
    savedConfigurationDescription:'Es wurde eine gespeicherte Konfiguration gefunden. Sie können dort fortfahren, wo Sie aufgehört haben, oder eine neue Konfiguration starten.',
    startConfiguration: 'Konfiguration starten',
    continueConfiguration: 'Konfiguration fortsetzen',
    newConfiguration: 'Neue Konfiguration',

    solidcostructionInfoTitle: "Hinweis für Massivbauwände",
    solidcostructionInfoText:"Für den Einbau in Massivbauwände ist eine Putzträgerplatte erforderlich. Diese ist nicht im Lieferumfang von Genulux enthalten und muss bauseits bereitgestellt werden.",


    quoteRequestTitle: "Angebot anfordern",

    quoteNamePlaceholder: "Vor- und Nachname",

    quoteCompanyPlaceholder: "Firma",

    quoteEmailPlaceholder: "E-Mail",

    quotePhonePlaceholder: "Telefon",

    quoteCountryPlaceholder: "Land",

    quoteCityPlaceholder: "Stadt",

    quoteMessagePlaceholder: "Nachricht",

    quoteSendButton: "Angebot anfordern",

    quoteSending: "Senden...",

    quoteSuccessMessage: "Anfrage erfolgreich gesendet. Wir werden Sie bald kontaktieren.",

    quoteErrorMessage: "Beim Senden der Anfrage ist ein Fehler aufgetreten.",

    quoteFormRequiredFields: "Bitte füllen Sie alle Pflichtfelder aus",

    quoteFieldRequired:
      'Pflichtfeld',

    quoteFieldInvalid:
      'Ungültiger Wert',

    quoteFieldTooLong:
      'Text zu lang',

    quoteNameLabel:
      'Name',

    quoteCompanyLabel:
      'Firma',

    quoteEmailLabel:
      'E-Mail',

    quotePhoneLabel:
      'Telefon',

    quoteCountryLabel:
      'Land',

    quoteCityLabel:
      'Ort',

    quoteMessageLabel:
      'Nachricht',

    quoteEmailInvalid:
      'Bitte geben Sie eine gültige E-Mail-Adresse ein',

    quotePhoneInvalid:
      'Bitte geben Sie eine gültige Telefonnummer ein',
  },

  es: {

    technicalMeasuresTitle: "Medidas técnicas",

    impressum: "Aviso legal",

    language: "Idioma",

    homeConfigurator: 'Inicio configurador',

    // Branding
    h1: "Genulux",
    h2: "Configurador",

    // Configurazione
    door: "Puerta",
    wallThickness: "Grosor de la pared",
    configurationStandard: "Estándar de configuración",

    // Riepilogo
    insertedMeasureType: "Tipo de medida ingresada",
    doorDimensions: "Medidas de la puerta",
    lightPassageDimensions: "Medidas del paso de luz",
    wallOpeningDimensions: "Medidas de la apertura de pared",

    // Misure
    measures: "Medidas",
    summary: "Resumen",
    insertMeasures: "Introducir las medidas",
    measureType: "Tipo de medida",
    standardMeasures: "Medidas estándar",
    customMeasures: "Medidas libres",
    width: "Ancho",
    height: "Alto",
    frame: "Marco",

    // Azioni
    continue: "Continuar",
    newConfiguration: "Nueva configuración",
    downloadPdf: "Descargar PDF",

    // Limiti
    min: "mín",
    max: "máx",

    // Documento PDF
    documentHeader: "Ficha técnica – Configuración de puerta",
    documentSubtitle: "Documento resumido",
    autoGenerated: "Documento generado automáticamente por el configurador",

    // Tipi di misura
    measureLuce: "Medida luz",
    measurePorta: "Medida puerta",
    measureMuro: "Apertura pared",

    // Standard
    standard: "Estándar",
    selectStandard: "Selecciona el estándar",
    selectStandardDescription: "Elige el estándar de configuración que se utilizará para el cálculo de las medidas.",
    international: "Internacional",
    germany: "DIN/Alemania",

    // Disponibilidad
    availability: "Disponibilidad",

    availabilityStock: "Disponible en stock",
    availabilityStockDelivery: "Entrega rápida",

    availabilityProduction: "Disponible bajo pedido",
    availabilityProductionDelivery: "Tiempos de entrega más largos",

    availabilityUnavailable: "Medida no disponible",
    availabilityContact: "Contactar con la oficina comercial",

    // tipo di porta
    woodDoor: 'Mader 40–44 mma',
    glassDoor: 'Vidri 8–12.7 mmo',

    // WALL TYPES
    wallType: 'Tipo de pared',
    massivbau: 'Construcción maciza',
    trockenbau: 'Construcción de paneles de yeso',

    // Tipo de pared - panelado de cartón yeso
    wallPanel: 'Panelado de cartón yeso',
    singlePanel: 'Panel simple',
    doublePanel: 'Panel doble',

 
    // Welcome configuratore

    welcomeTitle: "Bienvenido al configurador AGS",
    welcomeText1: "Configure su armazón para puerta corredera en unos sencillos pasos seleccionando las opciones que mejor se adapten a su proyecto.",
    welcomeText2: "Al finalizar la configuración obtendrá un resumen completo con todas las medidas y la información seleccionada.",

    welcomeDescription:'Configure su puerta en pocos pasos. Al finalizar podrá descargar un PDF con el resumen completo de las medidas.',
    welcomeFeaturesTitle: 'Durante la configuración deberá seleccionar:',
    welcomeFeatureDoor: 'Tipo de puerta',
    welcomeFeatureWallType: 'Tipo de pared',
    welcomeFeatureWallThickness: 'Espesor de la pared',
    welcomeFeatureMeasures: 'Medidas de la puerta',
    savedConfigurationTitle: 'Configuración guardada encontrada',
    savedConfigurationDescription:'Se ha encontrado una configuración guardada. Puede continuar donde lo dejó o iniciar una nueva configuración.',
    startConfiguration: 'Iniciar configuración',
    continueConfiguration: 'Continuar configuración',
    newConfiguration: 'Nueva configuración',

    solidcostructionInfoTitle: "Información para muros de mampostería",
    solidcostructionInfoText:"Para la instalación en muros de mampostería es necesario utilizar un panel portaenlucido. Este panel no está incluido en el suministro de Genulux y debe adquirirse por separado.",



    quoteRequestTitle: "Solicitar presupuesto",

    quoteNamePlaceholder: "Nombre y apellidos",

    quoteCompanyPlaceholder: "Empresa",

    quoteEmailPlaceholder: "Correo electrónico",

    quotePhonePlaceholder: "Teléfono",

    quoteCountryPlaceholder: "País",

    quoteCityPlaceholder: "Ciudad",

    quoteMessagePlaceholder: "Mensaje",

    quoteSendButton: "Solicitar presupuesto",

    quoteSending: "Enviando...",

    quoteSuccessMessage: "Solicitud enviada correctamente. Nos pondremos en contacto pronto.",

    quoteErrorMessage: "Se produjo un error al enviar la solicitud.",

    quoteFormRequiredFields: "Complete todos los campos obligatorios",

    quoteFieldRequired:
      'Campo obligatorio',

    quoteFieldInvalid:
      'Valor no válido',

    quoteFieldTooLong:
      'Texto demasiado largo',

    quoteNameLabel:
      'Nombre',

    quoteCompanyLabel:
      'Empresa',

    quoteEmailLabel:
      'Correo electrónico',

    quotePhoneLabel:
      'Teléfono',

    quoteCountryLabel:
      'País',

    quoteCityLabel:
      'Ciudad',

    quoteMessageLabel:
      'Mensaje',

    quoteEmailInvalid:
      'Introduzca un correo electrónico válido',

    quotePhoneInvalid:
      'Introduzca un número de teléfono válido',
  },

  fr: {

    technicalMeasuresTitle: "Mesures techniques",

    impressum: "Mentions légales",

    language: "Langue",

    homeConfigurator: 'Accueil configurateur',

    // Branding
    h1: "Genulux",
    h2: "Configurateur",

    // Configurazione
    door: "Porte",
    wallThickness: "Épaisseur du mur",
    configurationStandard: "Standard de configuration",

    // Riepilogo
    insertedMeasureType: "Type de mesure saisie",
    doorDimensions: "Dimensions de la porte",
    lightPassageDimensions: "Dimensions du passage libre",
    wallOpeningDimensions: "Dimensions de l'ouverture du mur",

    // Misure
    measures: "Mesures",
    summary: "Résumé",
    insertMeasures: "Saisir les mesures",
    measureType: "Type de mesure",
    standardMeasures: "Mesures standard",
    customMeasures: "Mesures personnalisées",
    width: "Largeur",
    height: "Hauteur",
    frame: "Huisserie",

    // Azioni
    continue: "Continuer",
    newConfiguration: "Nouvelle configuration",
    downloadPdf: "Télécharger le PDF",

    // Limiti
    min: "min",
    max: "max",

    // Documento PDF
    documentHeader: "Fiche technique – Configuration de porte",
    documentSubtitle: "Document récapitulatif",
    autoGenerated: "Document généré automatiquement par le configurateur",

    // Tipi di misura
    measureLuce: "Mesure du passage libre",
    measurePorta: "Mesure de la porte",
    measureMuro: "Ouverture du mur",

    // Standard
    standard: "Standard",
    selectStandard: "Sélectionnez le standard",
    selectStandardDescription: "Choisissez le standard de configuration à utiliser pour le calcul des mesures.",
    international: "International",
    germany: "DIN/Allemagne",

    // Disponibilité
    availability: "Disponibilité",
    
    availabilityStock: "Disponible en stock",
    availabilityStockDelivery: "Livraison rapide",

    availabilityProduction: "Disponible sur commande",
    availabilityProductionDelivery: "Délais de livraison plus longs",

    availabilityUnavailable: "Dimension non disponible",
    availabilityContact: "Contacter notre service commercial",

    // Tipo di porta
    woodDoor: 'Bois 40–44 mm',
    glassDoor: 'Verre 8–12.7 mm',

    // WALL TYPES
    wallType: 'Type de mur',
    massivbau: 'Construction massive',
    trockenbau: 'Construction en plaques de plâtre',

    // Type de mur - panneaux en plaques de plâtre
    wallPanel: 'Panneau de plaque de plâtre',
    singlePanel: 'Panneau simple',
    doublePanel: 'Double panneau',

    
    // Welcome configuratore

    welcomeTitle: "Bienvenue dans le configurateur AGS",
    welcomeText1: "Configurez votre châssis pour porte coulissante en quelques étapes simples selon vos besoins.",
    welcomeText2: "À la fin de la configuration, vous obtiendrez un récapitulatif complet avec toutes les dimensions et les informations sélectionnées.",

    welcomeDescription:'Configurez votre porte en quelques étapes. À la fin, vous pourrez télécharger un PDF récapitulatif avec toutes les dimensions.',
    welcomeFeaturesTitle: 'Pendant la configuration, vous devrez sélectionner :',
    welcomeFeatureDoor: 'Type de porte',
    welcomeFeatureWallType: 'Type de cloison',
    welcomeFeatureWallThickness: 'Épaisseur de la cloison',
    welcomeFeatureMeasures: 'Dimensions de la porte',
    savedConfigurationTitle: 'Configuration enregistrée trouvée',
    savedConfigurationDescription:'Une configuration enregistrée a été trouvée. Vous pouvez reprendre où vous vous étiez arrêté ou commencer une nouvelle configuration.',
    startConfiguration: 'Commencer la configuration',
    continueConfiguration: 'Continuer la configuration',
    newConfiguration: 'Nouvelle configuration',

    solidcostructionInfoTitle: "Information pour les murs maçonnés",
    solidcostructionInfoText:"Pour une installation dans un mur maçonné, un panneau support d'enduit est nécessaire. Ce panneau n'est pas fourni par Genulux et doit être approvisionné séparément.",


    quoteRequestTitle: "Demander un devis",

    quoteNamePlaceholder: "Nom et prénom",

    quoteCompanyPlaceholder: "Entreprise",

    quoteEmailPlaceholder: "E-mail",

    quotePhonePlaceholder: "Téléphone",

    quoteCountryPlaceholder: "Pays",

    quoteCityPlaceholder: "Ville",

    quoteMessagePlaceholder: "Message",

    quoteSendButton: "Demander un devis",

    quoteSending: "Envoi...",

    quoteSuccessMessage: "Demande envoyée avec succès. Nous vous contacterons bientôt.",

    quoteErrorMessage: "Une erreur s'est produite lors de l'envoi de la demande.",

    quoteFormRequiredFields: "Veuillez remplir tous les champs obligatoires",

    quoteFieldRequired:
      'Champ obligatoire',

    quoteFieldInvalid:
      'Valeur invalide',

    quoteFieldTooLong:
      'Texte trop long',

    quoteNameLabel:
      'Nom',

    quoteCompanyLabel:
      'Entreprise',

    quoteEmailLabel:
      'E-mail',

    quotePhoneLabel:
      'Téléphone',

    quoteCountryLabel:
      'Pays',

    quoteCityLabel:
      'Ville',

    quoteMessageLabel:
      'Message',

    quoteEmailInvalid:
      'Saisissez une adresse e-mail valide',

    quotePhoneInvalid:
      'Saisissez un numéro de téléphone valide',
  }
}
